name: macros_screwdriver
description: A collection of helpful macros to reduce boilerplate code and make development easier.
version: 0.1.0

repository: https://github.com/birjuvachhani/macros_screwdriver

environment:
  sdk: ^3.6.0-261.0.dev

# Add regular dependencies here.
dependencies:
  macros: ^0.1.3-main.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
